### PR TITLE
fix(data.js): replace the join method of visual path

### LINKED ISSUE #149: Stop using path.join to manipulate URL
It doesn't work on Windows. `path.join` sees `/...` and treats it as `C:\...`. The output won't be valid URL. Use the `URL` class's `new URL(path, base)` instead.

Read the following MDN document to learn about how to use `new URL(path, base)` as a way to concatenate path: https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

Look into this file and find all the `path.join` and `path.resolve` calls: https://github.com/avocadotoastlive/avocadotoast.live/blob/master/_data/data.js. Not all of them need to be corrected. Only those dealing with "virtual path" need to be updated. (Virtual path means a path used in URL instead of local file system.)

`url.resolve` could be a good replacement here, but it's deprecated. Here's how to use `URL` class to implement the `url.resolve` function: https://nodejs.org/api/url.html#url_url_resolve_from_to

### PR DESCRIPTION
**Pull request by Bittttter**
Path.join doesn't work on windows, so use URL class instead.

This MR fix #149

### CODE REVIEW

File: _data/data.js [hunk 1]
```diff
@@ -7,6 +7,19 @@ const Parser = require('rss-parser');
 const Axios = require('axios');
 const Sharp = require('sharp');
 
+const uriJoin = (...paths) => {
+  if (!Array.isArray(paths))
+    return new TypeError('TypeError: uriJoin must have at least one param');
+  const resolvedUrl = [].reduce.call(paths, (prev, curr) => {
+    return new URL(curr, new URL(prev + '/', 'resolve://'));
```
Comment (CatChen) [inline _data/data.js:14]: We need to give some special treatment to that extra `'/'` you append to `prev`. I understand why you did that -- when `prev` doesn't end with a `/` the last segment of `prev` will be replaced by `curr`. That was actually the intended behavior of `url.resolve`:

```
url.resolve('/one/two/three', 'four');         // '/one/two/four'
```

We can see that `three` is replaced by `four` instead of becoming `three/four`. We don't want exactly the same behavior. However, we need to deal with this case:

```
uriJoin('/one/', 'two');         // '/one//two'
```

We should use use `prev.endsWith('/')` to determine whether we want to append another `/`.

```suggestion
    return new URL(curr, new URL(prev.endsWith('/') ? prev : prev + '/', 'resolve://'));
```

**Review by CatChen — CHANGES_REQUESTED** [review]
See inline comments

File: _data/data.js [hunk 2]
```diff
@@ -362,10 +373,12 @@ const resizeImage = async function (filename) {
         }
       })(),
       */
+        const pngVirtualPath = urlJoin(path, `${file}@${size}w.png`);
+```<span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/avocadotoastlive/avocadotoast.live/163?utm_source=unchanged-line-comment">Graphite</a>.</span>
```
Comment (CatChen) [inline _data/data.js:377]: Removed code generated by Graphite comment.

```suggestion
```

File: _data/data.js [hunk 3]
```diff
@@ -18,8 +31,9 @@ const XIMALAYA_RSS_URL = 'https://www.ximalaya.com/album/29161862.xml';
 // __dirname is the _data directory
 const IMAGE_PATH = '/images/external/';
 const IMAGE_DIRECTORY = Path.resolve(__dirname, '../images/external/');
+// NETLIFY_BUILD_BASE may be a reference url, so see it as visual url..
 const IMAGE_CACHE_DIRECTORY = process.env.NETLIFY
-  ? Path.join(process.env.NETLIFY_BUILD_BASE, 'cache/', 'images/external/')
+  ? uriJoin(process.env.NETLIFY_BUILD_BASE, 'cache/', 'images/external/')
```
Comment (CatChen) [inline _data/data.js:36]:
```suggestion
  ? Path.join(process.env.NETLIFY_BUILD_BASE, 'cache/', 'images/external/')
```

File: _data/data.js [hunk 4]
```diff
@@ -18,8 +31,9 @@ const XIMALAYA_RSS_URL = 'https://www.ximalaya.com/album/29161862.xml';
 // __dirname is the _data directory
 const IMAGE_PATH = '/images/external/';
 const IMAGE_DIRECTORY = Path.resolve(__dirname, '../images/external/');
+// NETLIFY_BUILD_BASE may be a reference url, so see it as visual url..
```
Comment (CatChen) [inline _data/data.js:34]:
```suggestion
```

**Review by CatChen — APPROVED** [review]
